name: test-service
services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db
    container_name: test_app

  db:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --skip-character-set-client-handshake
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/config/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/initdb:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=test_user
      - MYSQL_PASSWORD=test_password
    container_name: test_db
